spring:
  application:
    name: spring-boot-04-restjpa
  datasource:
    url: jdbc:mysql://localhost:3306;databaseName=EA_Project
    username: root
    password: Itsmey0n@s
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#logging:
#  file:
#    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8004
